### ISSUE TITLE
Add required packages / libs to readme

### ISSUE THREAD

**Issue by phip1611** [Shriram-Balaji/cli-hex-rgb#1]
Hi,
I found your crate on crates.io and I think it's quite cool. I had to install the following packages on ubuntu to run `cargo install hex-rgb` 

`$ sudo apt install libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev`

Maybe you can add it to READMe.md?

**Comment by shrirambalaji** [comment]
@phip1611 thanks! will add it to the Readme

**Comment by shrirambalaji** [comment]
@phip1611  Added it to the readme, thanks again for taking time to try out hex-rgb and mentioning this issue :D
